apiVersion: batch/v1
kind: Job
metadata:
  name: {{jobName}}
spec:
  completions: 1  # Job should successfully complete at least once
  parallelism: 1  # Number of pods to run at the same time
  backoffLimit: 0  # Ensures no retries after failure
  ttlSecondsAfterFinished: 1  # Job and its pods are deleted 1 second after completion
  template:
    spec:
      hostNetwork: true
      containers:
      - name: cs-server-container
        #image: goldsourceservers/cstrike
        image: localhost:5000/cs16-server:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            printenv && ls -al && exec ./hlds_run -game cstrike +port {{port}} +maxplayers 10 +map {{mapName}} -dlls -norestart
        ports:
        - containerPort: {{port}}
          protocol: UDP
      restartPolicy: Never
